apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials-sync
  labels:
    app: counter-service
spec:
  # ESO will check AWS every hour for rotation/changes
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    # This must match what we put in backend-deployment.yaml exactly
    name: rds-credentials 
    creationPolicy: Owner
  data:
    - secretKey: password # The key inside the K8s Secret
      remoteRef:
        # The exact name of the secret in AWS Secrets Manager
        key: ehud-counter-service-rds-credentials