{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: counter-backend-scaler
  labels:
    app: counter-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-backend
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: prometheus
      metadata:
        query: 'sum(rate(http_requests_total{exported_endpoint="/api/counter"}[1m]))'
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        threshold: "{{ .Values.keda.targetRequestsPerSecond }}"
{{- end }}