apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app: counter-service
spec:
  provider:
    aws:
      service: SecretsManager
      # Pulling the exact region dynamically from our values.yaml
      region: "{{ .Values.global.awsRegion }}"