apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: counter-backend-monitor
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: counter-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s