name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-west-2"
  BACKEND_ECR: "630943284793.dkr.ecr.eu-west-2.amazonaws.com/ehud-counter-backend"
  FRONTEND_ECR: "630943284793.dkr.ecr.eu-west-2.amazonaws.com/ehud-counter-frontend"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::630943284793:role/ehud-counter-service-terraform-ci
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tags
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: |
            ${{ env.BACKEND_ECR }}:latest
            ${{ env.BACKEND_ECR }}:${{ env.sha_short }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.FRONTEND_ECR }}:latest
            ${{ env.FRONTEND_ECR }}:${{ env.sha_short }}